version: '3.8'

services:
  db:
    container_name: aspeiacs-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 36112154
      POSTGRES_DB: ASPEIA_CS
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d ASPEIA_CS']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: aspeiacs_postgres_data
