-- CreateTable
CREATE TABLE "WORKSPACE" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WORKSPACE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USUARIO_WORKSPACE" (
    "usuarioId" INTEGER NOT NULL,
    "workspaceId" INTEGER NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'member',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USUARIO_WORKSPACE_pkey" PRIMARY KEY ("usuarioId","workspaceId")
);

-- CreateIndex
CREATE INDEX "USUARIO_WORKSPACE_usuarioId_idx" ON "USUARIO_WORKSPACE"("usuarioId");

-- CreateIndex
CREATE INDEX "USUARIO_WORKSPACE_workspaceId_idx" ON "USUARIO_WORKSPACE"("workspaceId");

-- AddForeignKey
ALTER TABLE "USUARIO_WORKSPACE" ADD CONSTRAINT "USUARIO_WORKSPACE_usuarioId_fkey" FOREIGN KEY ("usuarioId") REFERENCES "USUARIO"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USUARIO_WORKSPACE" ADD CONSTRAINT "USUARIO_WORKSPACE_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "WORKSPACE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
