-- CreateTable
CREATE TABLE "CRMTag" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "color" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CRMTag_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_CRMOrganizationToCRMTag" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,

    CONSTRAINT "_CRMOrganizationToCRMTag_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_CRMPersonToCRMTag" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,

    CONSTRAINT "_CRMPersonToCRMTag_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateTable
CREATE TABLE "_CRMLeadToCRMTag" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL,

    CONSTRAINT "_CRMLeadToCRMTag_AB_pkey" PRIMARY KEY ("A","B")
);

-- CreateIndex
CREATE UNIQUE INDEX "CRMTag_name_key" ON "CRMTag"("name");

-- CreateIndex
CREATE INDEX "_CRMOrganizationToCRMTag_B_index" ON "_CRMOrganizationToCRMTag"("B");

-- CreateIndex
CREATE INDEX "_CRMPersonToCRMTag_B_index" ON "_CRMPersonToCRMTag"("B");

-- CreateIndex
CREATE INDEX "_CRMLeadToCRMTag_B_index" ON "_CRMLeadToCRMTag"("B");

-- AddForeignKey
ALTER TABLE "_CRMOrganizationToCRMTag" ADD CONSTRAINT "_CRMOrganizationToCRMTag_A_fkey" FOREIGN KEY ("A") REFERENCES "CRMOrganization"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_CRMOrganizationToCRMTag" ADD CONSTRAINT "_CRMOrganizationToCRMTag_B_fkey" FOREIGN KEY ("B") REFERENCES "CRMTag"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_CRMPersonToCRMTag" ADD CONSTRAINT "_CRMPersonToCRMTag_A_fkey" FOREIGN KEY ("A") REFERENCES "CRMPerson"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_CRMPersonToCRMTag" ADD CONSTRAINT "_CRMPersonToCRMTag_B_fkey" FOREIGN KEY ("B") REFERENCES "CRMTag"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_CRMLeadToCRMTag" ADD CONSTRAINT "_CRMLeadToCRMTag_A_fkey" FOREIGN KEY ("A") REFERENCES "CRMLead"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_CRMLeadToCRMTag" ADD CONSTRAINT "_CRMLeadToCRMTag_B_fkey" FOREIGN KEY ("B") REFERENCES "CRMTag"("id") ON DELETE CASCADE ON UPDATE CASCADE;
